### ISSUE TITLE
I can't find the results

### ISSUE THREAD

**Issue by richard1230** [gwen001/google-search#1]
steps to Reproduce:
1.(here is my fbcookie),type the following:
export FACEBOOK_COOKIE="datr=MxeTYYDWGsmV9ARPWSunVXgF; sb=rkDNXTi8IihoyW-M_C3DshIB; c_user=100029018674116; xs=46%3AQy-iCXDGPQ%3A2%3A1644807957%3A-1%3A3373%3A%3AAcWENdtfu4uRHutJ7ZBGeDjRWrgAyNvIRA0rr8Ir4jI; fr=0iCFrRQLqE2cYd7yp.AWWeIEbaCqNSw.Bjnybs.a9.AAA.0.0.BjrrB7.AWVT1tbE8_A; wd=1440x298; dpr=2; presence=C%7B%%22utc3%22%3A16723%22v%22%3A1%7D"

2.type the following:
google-search -s "site:10degres.net" -c "$FACEBOOK_COOKIE"

I can't see any results! I don't know why!!!

**Comment by gwen001** [comment]
Same for me, doesn't work anymore, maybe Google/Facebook fixed this.
